In [180]:
import pandas as pd 
import numpy as numpy
import matplotlib.pyplot as pyplot
import seaborn as sns

In [181]:
df= pd.read_csv("heart_disease.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target_binary
0,63.000000,1,1,145.000000,233.000000,1,2,150.000000,0,2.300000,3,0.0,6.0,0
1,67.000000,1,4,160.000000,286.000000,0,2,108.000000,1,1.500000,2,3.0,3.0,1
2,67.000000,1,4,120.000000,229.000000,0,2,129.000000,1,2.600000,2,2.0,7.0,1
3,37.000000,1,3,130.000000,250.000000,0,0,187.000000,0,3.500000,3,0.0,3.0,0
4,41.000000,0,2,130.000000,204.000000,0,2,172.000000,0,1.400000,1,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1019,60.072205,1,3,115.422056,181.768595,0,0,128.155858,1,1.001941,2,1.0,7.0,1
1020,70.928404,1,2,166.727221,244.993631,1,0,108.481311,0,0.698337,2,1.0,7.0,1
1021,57.332875,1,2,105.075177,233.146324,0,2,140.342007,0,1.519138,1,0.0,7.0,1
1022,40.881554,0,4,125.068578,154.370678,1,2,123.756294,0,1.936684,2,1.0,7.0,1
1023,46.863367,1,3,121.909777,291.175476,1,2,146.652276,1,1.913951,2,2.0,3.0,1

In [182]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            1024 non-null   float64
 1   sex            1024 non-null   int64
 2   cp             1024 non-null   int64
 3   trestbps       1024 non-null   float64
 4   chol           1024 non-null   float64
 5   fbs            1024 non-null   int64
 6   restecg        1024 non-null   int64
 7   thalach        1024 non-null   float64
 8   exang          1024 non-null   int64
 9   oldpeak        1024 non-null   float64
 10  slope          1024 non-null   int64
 11  ca             1024 non-null   float64
 12  thal           1024 non-null   float64
 13  target_binary  1024 non-null   int64
dtypes: float64(7), int64(7)
memory usage: 112.1 KB

In [183]:
df.isna().sum()

age              0
sex              0
cp               0
trestbps         0
chol             0
fbs              0
restecg          0
thalach          0
exang            0
oldpeak          0
slope            0
ca               0
thal             0
target_binary    0
dtype: int64

In [184]:
df.duplicated().sum()

np.int64(0)

In [185]:
df["sex"].value_counts()

sex
1    702
0    322
Name: count, dtype: int64

In [186]:
df["sex"]=df["sex"].map({1:"Male", 0:"Female"},inplace=True)

In [187]:
print(df["cp"].value_counts())

cp
4    485
3    293
2    160
1     86
Name: count, dtype: int64

In [188]:
df["cp"] = df["cp"].map({1:"Typical Angina", 2:"Atypical Angina", 3:"Non-anginal Pain", 4:"Asymptomatic"})

In [189]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target_binary
0,63.0,Male,Typical Angina,145.0,233.0,1,2,150.0,0,2.3,3,0.0,6.0,0
1,67.0,Male,Asymptomatic,160.0,286.0,0,2,108.0,1,1.5,2,3.0,3.0,1
2,67.0,Male,Asymptomatic,120.0,229.0,0,2,129.0,1,2.6,2,2.0,7.0,1
3,37.0,Male,Non-anginal Pain,130.0,250.0,0,0,187.0,0,3.5,3,0.0,3.0,0
4,41.0,Female,Atypical Angina,130.0,204.0,0,2,172.0,0,1.4,1,0.0,3.0,0

In [190]:
df["fbs"].value_counts()

fbs
0    855
1    169
Name: count, dtype: int64

In [191]:
df["fbs"] = df["fbs"].map({0:"≤120 mg/dl(Normal)", 1:">120 mg/dl(High)"})

In [192]:
df["restecg"] = df["restecg"].map({0:"Normal", 1:"ST-T Abnormality", 2:"Left Ventricular Hypertrophy"})

In [193]:
df["exang"] = df["exang"].map({0:"No", 1:"Yes"})

In [194]:
df["slope"] = df["slope"].map({1:"Upsloping", 2:"Flat", 3:"Downsloping"})

In [195]:
df["thal"] = df["thal"].map({3:"Normal", 6:"Fixed Defect", 7:"Reversible Defect"})

In [196]:
df["target_binary"] = df["target_binary"].map({0: "No Heart Disease", 1: "Heart Disease"})

In [197]:
categorical_cols = ["sex", "cp", "fbs", "restecg", "exang", "slope", "thal", "target_binary"]

for col in categorical_cols:
    print(f"{col}: {df[col].unique()}")

sex: <ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
cp: <ArrowStringArray>
['Typical Angina', 'Asymptomatic', 'Non-anginal Pain', 'Atypical Angina']
Length: 4, dtype: str
fbs: <ArrowStringArray>
['>120 mg/dl(High)', '≤120 mg/dl(Normal)']
Length: 2, dtype: str
restecg: <ArrowStringArray>
['Left Ventricular Hypertrophy', 'Normal', 'ST-T Abnormality']
Length: 3, dtype: str
exang: <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
slope: <ArrowStringArray>
['Downsloping', 'Flat', 'Upsloping']
Length: 3, dtype: str
thal: <ArrowStringArray>
['Fixed Defect', 'Normal', 'Reversible Defect']
Length: 3, dtype: str
target_binary: <ArrowStringArray>
['No Heart Disease', 'Heart Disease']
Length: 2, dtype: str

In [198]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target_binary
0,63.0,Male,Typical Angina,145.0,233.0,>120 mg/dl(High),Left Ventricular Hypertrophy,150.0,No,2.3,Downsloping,0.0,Fixed Defect,No Heart Disease
1,67.0,Male,Asymptomatic,160.0,286.0,≤120 mg/dl(Normal),Left Ventricular Hypertrophy,108.0,Yes,1.5,Flat,3.0,Normal,Heart Disease
2,67.0,Male,Asymptomatic,120.0,229.0,≤120 mg/dl(Normal),Left Ventricular Hypertrophy,129.0,Yes,2.6,Flat,2.0,Reversible Defect,Heart Disease
3,37.0,Male,Non-anginal Pain,130.0,250.0,≤120 mg/dl(Normal),Normal,187.0,No,3.5,Downsloping,0.0,Normal,No Heart Disease
4,41.0,Female,Atypical Angina,130.0,204.0,≤120 mg/dl(Normal),Left Ventricular Hypertrophy,172.0,No,1.4,Upsloping,0.0,Normal,No Heart Disease